### ISSUE TITLE
Get province working in the app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-canada#121]
@nikhilwoodruff could you advise?

<img width="492" alt="image" src="https://user-images.githubusercontent.com/6076111/215219512-52979172-8f10-4724-abfd-583d2061ded1.png">

https://policyengine.org/ca/household?focus=household.demographic.geographic.province.province.province&household=1096

**Comment by nikhilwoodruff** [comment]
Variables need to be yearly to show up (province is defined for `ETERNITY` right now)
