### ISSUE TITLE
Michigan Income Tax rate

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-canada#246]
[Reference](https://taxfoundation.org/state/michigan/)

**Comment by MaxGhenis** [comment]
FYI you can `Transfer issue` between repos in the bottom right

<img width="303" alt="image" src="https://user-images.githubusercontent.com/6076111/233739060-6c33d097-c620-46df-8882-cf1535844845.png">

**Comment by PavelMakarchuk** [comment]
great to know!

Am Fr., 21. Apr. 2023 um 17:42 Uhr schrieb Max Ghenis <
***@***.***>:
